import os
import uuid
import boto3
from botocore.client import Config
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
import tweepy

# ===========================
# Wasabi / S3 configuration
# ===========================
WASABI_BUCKET = os.getenv("WASABI_BUCKET")
WASABI_ENDPOINT = "https://s3.ap-southeast-1.wasabisys.com"
ACCESS_KEY = os.getenv("WASABI_ACCESS_KEY")
SECRET_KEY = os.getenv("WASABI_SECRET_KEY")

s3_client = boto3.client(
    "s3",
    aws_access_key_id=ACCESS_KEY,
    aws_secret_access_key=SECRET_KEY,
    endpoint_url=WASABI_ENDPOINT,
    config=Config(signature_version="s3v4")
)

# ===========================
# X / Twitter
# ===========================
def post_to_x(message, video_file_path):
    client = tweepy.Client(
        consumer_key=os.getenv("X_API_KEY"),
        consumer_secret=os.getenv("X_API_SECRET"),
        access_token=os.getenv("X_ACCESS_TOKEN"),
        access_token_secret=os.getenv("X_ACCESS_SECRET")
    )
    media = client.media_upload(filename=video_file_path)
    client.create_tweet(text=message, media_ids=[media.media_id])

# ===========================
# YouTube
# ===========================
def post_to_youtube(title, description, video_file_path):
    youtube = build(
        "youtube", "v3",
        developerKey=os.getenv("YOUTUBE_API_KEY")
    )
    request = youtube.videos().insert(
        part="snippet,status",
        body={
            "snippet": {"title": title, "description": description},
            "status": {"privacyStatus": "public"}
        },
        media_body=MediaFileUpload(video_file_path)
    )
    return request.execute()

# ===========================
# Download video from Wasabi
# ===========================
def download_video_from_wasabi(key, local_path):
    s3_client.download_file(WASABI_BUCKET, key, local_path)

# ===========================
# Orchestrator: generate + upload + post
# ===========================
def run_orchestrator():
    try:
        # 1️⃣ Generate dummy AI video
        video_content = b"This is a dummy AI-generated video."
        filename = f"runs/video_{uuid.uuid4().hex}.mp4"

        print(f"[Orchestrator] Created video: {filename}")

        # 2️⃣ Upload to Wasabi
        s3_client.put_object(
            Bucket=WASABI_BUCKET,
            Key=filename,
            Body=video_content,
            ContentType="video/mp4"
        )
        print(f"[Orchestrator] Uploaded to Wasabi: {filename}")

        # Download for posting
        local_file = f"/tmp/{uuid.uuid4().hex}.mp4"
        download_video_from_wasabi(filename, local_file)

        # 3️⃣ Post to social media
        post_to_x("Check out this AI-generated video!", local_file)
        yt_response = post_to_youtube("AI Video", "Generated by faceless AI", local_file)

        print("[Orchestrator] Posted to X and YouTube")

        return {
            "status": "ok",
            "wasabi_key": filename,
            "youtube_response": yt_response
        }

    except Exception as e:
        print(f"[Orchestrator] Error: {str(e)}")
        return {"status": "error", "error": str(e)}
def run_orchestrator():
    try:
        print("Orchestrator started")

        # 👇 CALL YOUR EXISTING LOGIC HERE
        result = orchestrate()   # or whatever your main function is called

        return {
            "status": "ok",
            "result": result
        }

    except Exception as e:
        print("Orchestrator error:", str(e))
        return {
            "status": "error",
            "error": str(e)
        }
       
        

